### ISSUE TITLE
Unable to export session on Firefox

### ISSUE THREAD

**Issue by jacobhilker1** [SHiLLySiT/IronWriter#22]
I am really enjoying the software so far, yet when I try to save clicking the export session nothing pops up.

**Comment by SHiLLySiT** [comment]
Hi @jacobhilker1! The app automatically saves data to the browser which should automatically be restored when you come back to the page on the same device. The export feature was provided as a way to export the data for backup/portability. 

However it does sound like the export feature isn't working. When the button is clicked the browser _should_ automatically start a download of the exported data without any sort of popup. 

**What browser and device are you using?**

**Comment by jacobhilker1** [comment]
I was using Windows 10 and Firefox. I would have to go back and double
check the specific versions of each.

**Comment by SHiLLySiT** [comment]
@jacobhilker1 Thanks for the details! It seems the way I've setup exporting doesn't work in Firefox. I'll take a look at fixing it.

**Comment by SHiLLySiT** [comment]
Hmm I did confirm that this was broken for me yesterday, but after attempting to reproduce it _today_ it appears to be working. @jacobhilker1 Can you confirm that its also working for you? Also please let me know what version of Firefox you're using. Thanks!

**Comment by jacobhilker1** [comment]
I don't remember the exact Firefox version, but I will test again today
with the current version of Firefox. I will also test the offline version I
have as well.

**Comment by cilestin** [comment]
Running windows 10 with Firefox 71.0 and exporting works for me.

**Comment by jacobhilker1** [comment]
right now it works for me as well.
