### ISSUE TITLE
Add ability to remove items and assets

### ISSUE THREAD

**Issue by SHiLLySiT** [SHiLLySiT/IronWriter#27]
As mentioned in #25, there should be a way to remove items that you no longer need e.g. ones that have 0 quantity.

Additionally assets should be removable as well as assets can be removed during normal play e.g. "Slain Companions" section in the official rulebook.

**Comment by cilestin** [comment]
Been wondering what sort of tag "standard" would be the best way to do this.  There is currently the `bond`/`unbond` and `is`/`not` tags - which leads me to think that maybe there should be `asset`/`removeAsset` (or `unasset`? ... probably not 😉 ).

However, there's also `progress x complete` that removes the named progress, so `asset  x remove` makes some sense too.

I think to keep asset/item properties as open as possible (maybe an asset/item "needs" a `Removed` property to be set?), I'd lean toward `assetRemove`, but that's just, like, my opinion, man.

**Comment by SHiLLySiT** [comment]
@cilestin Ah yes, I have not been very consistent with that. In retrospect I think `endprogress` would have been a better choice...and still might be something I fix! 🙃

The programmer side of me wants `assetremove` but I think most users would want the more grammatically correct way `removeasset`.

**Comment by cilestin** [comment]
@SHiLLySiT it's only v0.2 - you've got plenty of time to adjust as you go 👍 

I agree that `removeasset` and `removeitem` feel like the more natural way to go.

**Comment by SHiLLySiT** [comment]
Implemented by #27
