### ISSUE TITLE
Action Roll not working 

### ISSUE THREAD

**Issue by Valdus92** [SHiLLySiT/IronWriter#34]
Perhaps I don't know how to modify it. But when I pick a progress to roll the action die only rolls zeros. If I do not pick a progress it rolls normally.

**Comment by SHiLLySiT** [comment]
Hmm this might have been related to one of the bugs I just fixed in the [v0.3.2](https://github.com/SHiLLySiT/IronWriter/releases/tag/v0.3.2) as I'm not able to reproduce. Let me know if you still have problems tho
