### ISSUE TITLE
Asset management

### ISSUE THREAD

**Issue by Pipeline929** [SHiLLySiT/IronWriter#40]
I could just be misunderstanding things, but even the example in the documentation of how to use Ironwriter doesn't seem to work when adding assets to your character. To my understanding, I am to add an asset using the following format [asset Ritualist 1], the 1 being to add the first little pip to the asset. I am able to add an asset using [asset Ritualist], but when I add the 1 it clears the asset from my character's info. This tool is really interesting and I'd love to use it more but it's difficult to do so at this moment.

**Comment by SHiLLySiT** [comment]
Ah yeah the docs are a bit misleading, but the tags aren't super intuitive either 😅. You have to use `[asset Ritualist]` first to add the asset, then use `[asset Ritualist 1]` to add the first pip. You can't do it all in one tag.
